### ISSUE TITLE
Errors when using option -m broadcast 

### ISSUE THREAD

**Issue by redbull05689** [assemblerflow/flowcraft#232]
I get the following error when I trying to use web service for flowcraft reports
````
flowcraft inspect -m broadcast 
Preparing broadcast data...
Traceback (most recent call last):
  File "/home/jbadmin/.local/bin/flowcraft", line 8, in <module>
    sys.exit(main())
  File "/home/jbadmin/.local/lib/python3.7/site-packages/flowcraft/flowcraft.py", line 459, in main
    inspect(args)
  File "/home/jbadmin/.local/lib/python3.7/site-packages/flowcraft/flowcraft.py", line 394, in inspect
    nf_inspect.broadcast_status()
  File "/home/jbadmin/.local/lib/python3.7/site-packages/flowcraft/generator/inspect.py", line 1564, in broadcast_status
    run_hash = self._get_run_hash()
  File "/home/jbadmin/.local/lib/python3.7/site-packages/flowcraft/generator/inspect.py", line 1541, in _get_run_hash
    with open(pipeline_path, "rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: "'nextflow/rnaseq-nf"
````
The following  results in the cli
```
flowcraft inspect 
```
![image](https://user-images.githubusercontent.com/37435176/81815106-4662b980-9532-11ea-9e44-ac3434ebc47d.png)

How I can resolve this issue?

**Comment by cimendes** [comment]
Hey! The server hosting the flowcraft's webapp is currently down. I'll let you know when we can get it up and running again! :)
