### ISSUE TITLE
UnicodeEncodeError when running build

### ISSUE THREAD

**Issue by pashadag** [assemblerflow/flowcraft#97]
I am having trouble with running the simple example and was wondering if you could help...

I just installed miniconda, then added bioconda channel, then install flowcraft via conda. The first thing I do is run the command:

flowcraft.py build -t "trimmomatic fastqc skesa pilon" -o my_pipeline.nf

I get the error pasted below on stderr.

Thanks for your help,
Paul

```
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 77: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1348, in build
    len(self.processes[1:]), len(self._fork_tree), self.lanes)))
Message: '\x1b[1;38m\tSuccessfully connected 4 process(es) with 0 fork(s) across 1 lane(s) \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 30: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1354, in build
    self._set_channels()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 869, in _set_channels
    "\tChannels set for {} \u2713".format(p.template)))
Message: '\x1b[1;38m\tChannels set for init \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 44: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1354, in build
    self._set_channels()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 869, in _set_channels
    "\tChannels set for {} \u2713".format(p.template)))
Message: '\x1b[1;38m\tChannels set for integrity_coverage \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 37: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1354, in build
    self._set_channels()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 869, in _set_channels
    "\tChannels set for {} \u2713".format(p.template)))
Message: '\x1b[1;38m\tChannels set for trimmomatic \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 32: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1354, in build
    self._set_channels()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 869, in _set_channels
    "\tChannels set for {} \u2713".format(p.template)))
Message: '\x1b[1;38m\tChannels set for fastqc \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 32: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1354, in build
    self._set_channels()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 869, in _set_channels
    "\tChannels set for {} \u2713".format(p.template)))
Message: '\x1b[1;38m\tChannels set for spades \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 46: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1360, in build
    len(self.secondary_inputs))))
Message: '\x1b[1;38m\tSuccessfully set 6 secondary input(s) \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 48: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1366, in build
    len(self.secondary_channels))))
Message: '\x1b[1;38m\tSuccessfully set 2 secondary channel(s) \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 32: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1373, in build
    "\tFinished configurations \u2713"))
Message: '\x1b[1;38m\tFinished configurations \u2713\x1b[0m'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/research/pzm11/miniconda3/lib/python3.6/logging/__init__.py", line 994, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2713' in position 41: ordinal not in range(128)
Call stack:
  File "/research/pzm11/miniconda3/bin/flowcraft", line 6, in <module>
    sys.exit(flowcraft.flowcraft.main())
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 290, in main
    build(args)
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/flowcraft.py", line 236, in build
    nfg.build()
  File "/research/pzm11/miniconda3/lib/python3.6/site-packages/flowcraft/generator/engine.py", line 1390, in build
    "\tPipeline written into {} \u2713".format(self.nf_file)))
Message: '\x1b[1;38m\tPipeline written into my_pipe.nf \u2713\x1b[0m'
Arguments: ()
```

**Comment by pashadag** [comment]
Thank you you are right. For the record, I added this line to .bashrc:

export LANG="en_US.UTF-8"

**Comment by tiagofilipe12** [comment]
Hello @pashadag thank you for your feedback. 
Now the print function `colored_print` checks for the presence of non-ascii characters when UTF-8 characters are not allowed by the user's system. If UTF-8 is not allowed then these characters will be removed from the strings being printed to the stdout.
